const pieces = [
    {
        "color": "black",
        "type": "rook",
        "row": 0,
        "col": 0,
    },
    {
        "color": "black",
        "type": "knight",
        "row": 0,
        "col": 1,
    },
    {
        "color": "black",
        "type": "bishop",
        "row": 0,
        "col": 2,
    },
    {
        "color": "black",
        "type": "king",
        "row": 0,
        "col": 3,
    },
    {
        "color": "black",
        "type": "queen",
        "row": 0,
        "col": 4,
    },
    {
        "color": "black",
        "type": "bishop",
        "row": 0,
        "col": 5,
    },
    {
        "color": "black",
        "type": "knight",
        "row": 0,
        "col": 6,
    },
    {
        "color": "black",
        "type": "rook",
        "row": 0,
        "col": 7,
    },
    {
        "color": "black",
        "type": "pawn",
        "row": 1,
        "col": 0,
    },
    {
        "color": "black",
        "type": "pawn",
        "row": 1,
        "col": 1,
    },
    {
        "color": "black",
        "type": "pawn",
        "row": 1,
        "col": 2,
    },
    {
        "color": "black",
        "type": "pawn",
        "row": 1,
        "col": 3,
    },
    {
        "color": "black",
        "type": "pawn",
        "row": 1,
        "col": 4,
    },
    {
        "color": "black",
        "type": "pawn",
        "row": 1,
        "col": 5,
    },
    {
        "color": "black",
        "type": "pawn",
        "row": 1,
        "col": 6,
    },
    {
        "color": "black",
        "type": "pawn",
        "row": 1,
        "col": 7,
    },
    {
        "color": "white",
        "type": "pawn",
        "row": 6,
        "col": 0,
    },
    {
        "color": "white",
        "type": "pawn",
        "row": 6,
        "col": 1,
    },
    {
        "color": "white",
        "type": "pawn",
        "row": 6,
        "col": 2,
    },
    {
        "color": "white",
        "type": "pawn",
        "row": 6,
        "col": 3,
    },
    {
        "color": "white",
        "type": "pawn",
        "row": 6,
        "col": 4,
    },
    {
        "color": "white",
        "type": "pawn",
        "row": 6,
        "col": 5,
    },
    {
        "color": "white",
        "type": "pawn",
        "row": 6,
        "col": 6,
    },
    {
        "color": "white",
        "type": "pawn",
        "row": 6,
        "col": 7,
    },
    {
        "color": "white",
        "type": "rook",
        "row": 7,
        "col": 0,
    },
    {
        "color": "white",
        "type": "knight",
        "row": 7,
        "col": 1,
    },
    {
        "color": "white",
        "type": "bishop",
        "row": 7,
        "col": 2,
    },
    {
        "color": "white",
        "type": "king",
        "row": 7,
        "col": 3,
    },
    {
        "color": "white",
        "type": "queen",
        "row": 7,
        "col": 4,
    },
    {
        "color": "white",
        "type": "bishop",
        "row": 7,
        "col": 5,
    },
    {
        "color": "white",
        "type": "knight",
        "row": 7,
        "col": 6,
    },
    {
        "color": "white",
        "type": "rook",
        "row": 7,
        "col": 7,
    }
];

module.exports = pieces;